sync:
  defaultIntervalMinutes: 40
  maxRetries: 3
  retryDelayMinutes: 5
  maxConcurrentRepos: 4
  delayBetweenReposSeconds: 30
  azure:
    baseUrl: https://dev.azure.com
    rateLimitPerMinute: 60
    burstLimit: 10
  notifications:
    enabled: true
    emails: []
  logging:
    level: info
    enableMetrics: true
repositories: []
scheduler:
  enabled: true
  lastRun: '2025-09-26T13:00:00.028Z'
  nextRun: '2025-09-26T13:40:00.028Z'
