# Configuração do actionlint para GitHub Actions workflows
# Documentação: https://github.com/rhysd/actionlint

# Configuração global
self-hosted-runner:
  # Labels personalizados para runners (se houver)
  labels: []
