version: 2

updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "lucianofronza"
    assignees:
      - "lucianofronza"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    ignore:
      # Ignorar atualizações major de algumas dependências críticas
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "lucianofronza"
    assignees:
      - "lucianofronza"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    ignore:
      # Ignorar atualizações major de React
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Sync Service dependencies
  - package-ecosystem: "npm"
    directory: "/sync-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "lucianofronza"
    assignees:
      - "lucianofronza"
    labels:
      - "dependencies"
      - "sync-service"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "lucianofronza"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci):"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker):"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker):"