groups:
  - name: indicadores-azure-alerts
    rules:
      # High Error Rate
      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High HTTP Error Rate
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP error rate"
          description: "HTTP error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s"

      # Database Connection Issues
      - alert: DatabaseConnectionIssues
        expr: database_connections > 20
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "Database has {{ $value }} active connections"

      # Cache Hit Rate Low
      - alert: LowCacheHitRate
        expr: rate(cache_hits_total[5m]) / (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m])) < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }}"

      # Sync Job Failures
      - alert: SyncJobFailures
        expr: rate(sync_jobs_total{status="failed"}[5m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Sync job failures detected"
          description: "{{ $value }} sync jobs failed in the last 5 minutes"

      # Azure API Rate Limit
      - alert: AzureAPIRateLimit
        expr: azure_api_rate_limit_remaining < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Azure API rate limit low"
          description: "Only {{ $value }} API calls remaining"

      # Service Down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.instance }} is down"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Disk Space Low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"} < 10
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value }}% available"

      # Pull Request Sync Issues
      - alert: PullRequestSyncIssues
        expr: rate(pull_requests_total[5m]) == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "No pull requests synced"
          description: "No pull requests have been synced in the last 5 minutes"

      # High Cycle Time
      - alert: HighCycleTime
        expr: histogram_quantile(0.95, rate(cycle_time_days_bucket[1h])) > 7
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "High cycle time detected"
          description: "95th percentile cycle time is {{ $value }} days"

      # High Review Time
      - alert: HighReviewTime
        expr: histogram_quantile(0.95, rate(review_time_days_bucket[1h])) > 2
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "High review time detected"
          description: "95th percentile review time is {{ $value }} days"

      # No Active Users
      - alert: NoActiveUsers
        expr: active_users == 0
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "No active users"
          description: "No active users for the last 30 minutes"

      # Redis Connection Issues
      - alert: RedisConnectionIssues
        expr: redis_connected_clients == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection issues"
          description: "No clients connected to Redis"

      # High Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate will expire in {{ $value | humanizeDuration }}"

      # Backup Failure
      - alert: BackupFailure
        expr: backup_last_success_timestamp < time() - 86400
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "Backup failure"
          description: "No successful backup in the last 24 hours"
